### ISSUE TITLE
Incorrect apostrophe encoding on Android

### ISSUE THREAD

**Issue by asvitzer** [PicnicSupermarket/localicious#24]
Hello!

We've started to use your toolchain for localization which has been great so far (good work 👍). The only issue we're having is with apostrophes.

**Problem**
When I use strings that have apostrophes for Android, they are encoded to the XML file using the unicode hex character code. That results in a compile-time error for Android Studio.

**To recreate**
If I take the example from your blog post (https://blog.picnic.nl/localizing-native-apps-made-easy-with-localicious-5063d02d3511):

```
ANDROID:
  CounterModule:
    CounterScreen:
      WelcomeLabel:
        COPY:
          en: "We're glad you're here!"
```

This will turn into the following XML after rendered:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="CounterModule_CounterScreen_WelcomeLabel_COPY">We&amp;apos;re glad you&#x27;re here!</string>
</resources>

```
That results in the following compile time error for Android Studio:

`(108: AAPT: error: unescaped apostrophe in string)`

**Possible Solutions**

1. Maybe I'm doing something wrong? Is there a proper way to input apostrophes that I've missed?
2. Surround strings with quotations when exporting them to Android. Change `strings_xml_file.hbs` to include quotations around `value` just as you're doing for the string name. And then do one of the following two:

- Remove any apostrophe conversion logic. The apostrophes will stay as typed into the localicipe. The strings XML output would then be: 
`<string name="CounterModule_CounterScreen_WelcomeLabel_COPY">"We're glad you're here!"</string> 
`
-  Change the unicode hex encoding to be HTML encoding instead. `&#x27;` becomes `&apos;`.  The XML output would be:  
`<string name="CounterModule_CounterScreen_WelcomeLabel_COPY">"We&apos;re glad you&apos;re here!"</string> `

3. Add an escape for apostrophes when they are input in the localicpe (similar to how `\\n` is converted to `\n`). Then the XML output ends up being:
`<string name="CounterModule_CounterScreen_WelcomeLabel_COPY">We\'re glad you\'re here!</string>`

**Comment by larslockefeer** [comment]
Hey @asvitzer, glad to hear that you are using Localicious and that it is working well for you 😁

Thanks a lot for your extensive bug report! I think we should go with solution 2, option 1 and have filed a PR.

Would you have an opportunity to checkout and run the code locally and verify that it works for you as well? Then we'll merge and cut a new release afterwards.

**Comment by asvitzer** [comment]
That was quick!

Just to make sure I did the local check correctly:

1) I cloned your branch `ll/android-encoding`
2) Ran localicious from the bin folder in your branch instead of running it from my yarn setup

If so, everything worked perfectly.

**Comment by larslockefeer** [comment]
Yep, that's what I was looking for! Did you also check that integrating the strings into your Android project does not yield unexpected results?

Asking because basically we now removed all HTML Entity encoding that handlebars was doing, so I just want to make sure that it does not break things for you elsewhere.

I have some thoughts about adding integration tests for this to the repo, but that is for some other time 😬

**Comment by asvitzer** [comment]
Yeah, our entire strings file was able to compile. 

I did have to make one change to our Localicipe file since the HTML encoding was removed. We were putting in ampersands as in `Pushberichten & cookies` and that had to be changed to `Pushberichten &amp; cookies`. Otherwise, Android Studio complained about the ampersand not being escaped in the XML output.

**Comment by larslockefeer** [comment]
Thanks @asvitzer! From a copywriter perspective, having to handle special characters in the Localicipe is not preferred, especially as different targets may have different escaping rules.

I opened a follow-up PR to handle [all characters](https://developer.android.com/guide/topics/resources/string-resource#FormattingAndStyling) that need to be escaped for the Android strings.xml file.

Could you verify once more for me that when running this branch locally will remove the aforementioned issue when integrating on Android? Then we'll merge and cut the release.

Thanks for your help 🙇

**Comment by asvitzer** [comment]
Makes sense, @larslockefeer! We'll get there slowly but surely. Don't worry. 💃🏽

I tested your latest changes and the only issue I found is that ampersands shouldn't be escaped when they are used as part of escaping a special character.

If I type `Who knew > Strings > Were Such > A Headache` in the localicipe

that renders to `<string name="String_me_along">"Who knew &amp;gt; Strings &amp;gt; Were Such &amp;gt; A Headache"</string>` in the final XML output.

And the IDE doesn't pick up that `&amp;gt;`  means >. Only if I change it to `&gt;` in the editor does it display correctly on a device.

**Comment by larslockefeer** [comment]
Of course 🤦‍♂️That can easily be fixed, I pushed a new commit to the PR 😁

**Comment by asvitzer** [comment]
Everything works great, @larslockefeer.

**Comment by larslockefeer** [comment]
Thanks!

**Comment by larslockefeer** [comment]
Release is out!
