### ISSUE TITLE
Typo on Swift

### ISSUE THREAD

**Issue by melisa-dlg** [PicnicSupermarket/localicious#27]
Hey guys! 
After spending some time translating all our copy into a Localicipe file, everything is looking great and the integration was painless! So thank you for that! Except for one little hiccup:

**Problem**
While installing my config file on my Xcode project, on the generated swift file there is a typo that throws a bunch of errors, nothing big but might be nice to fix it from your side instead of fixing the typo every time we run install 😅 

The generated struct looks like this:  `LocaliciousQuantity(quanitity: quantity)` 
which of course complains because it should be "quantity": `LocaliciousQuantity(quantity: quantity)`

Cheers!

**Comment by larslockefeer** [comment]
Hey @melisa-dlg, great to hear that the integration was painless except for this little hiccup 😁 We'll cut a release later today with the fix for your issue. Thanks for reporting!

**Comment by melisa-dlg** [comment]
Thanks for the quick response, I'll stay tuned  for the release 🎉

**Comment by larslockefeer** [comment]
Release is out!

**Comment by melisa-dlg** [comment]
👏  thanks!
