### ISSUE TITLE
Percentage encoding on Android

### ISSUE THREAD

**Issue by asvitzer** [PicnicSupermarket/localicious#30]
Hello,

Can percentages be added to the encoding substitution for the Android platform? 

Android Studio throws an error for strings that have a percentage in them but aren't format strings. An example:

`<string name="over_achiever">"Na het behalen van 100%"</string>`

If the `%` in the above string could become `&#37;` in the final strings XML file, that should fix the issue. And an exception should be added to not encode the percentage if it is included as part of a format string, as in `See all in %1{{s}}`

**Comment by larslockefeer** [comment]
Hey @asvitzer, thanks for the report. It should be fixed by the PR I just submitted, could you double-check for me? Then I'll merge and cut a new release.
