### ISSUE TITLE
Cannot find module 'commander'

### ISSUE THREAD

**Issue by lammertw** [PicnicSupermarket/localicious#5]
Running localicious gives me the following error:

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'commander'
Require stack:
- /Users/lwesterhoff/Developer/forks/localicious/bin/localicious
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/lwesterhoff/Developer/forks/localicious/bin/localicious:2:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/lwesterhoff/Developer/forks/localicious/bin/localicious' ]
}
```

**Comment by larslockefeer** [comment]
Hi @lammertw,

Thanks! We're still working out the last kinks before we can release 1.0 to npm and a report like this is very helpful.

For me, it works when I go through the following steps:

1. `git clone git@github.com:PicnicSupermarket/localicious.git && cd localicious`
2. `yarn install`
3. `node bin/localicious`

Can you share the steps that you went through that cause this to fail?

Once we are done with the 1.0 (most likely before the end of next week) we will publish the tool to npm such that it can be installed globally.

Also not that the syntax of the Localicipe will still change a bit today/tomorrow as a result of #3.

**Comment by lammertw** [comment]
The `yarn install` is missing from the `Requirements and installation` section so I didn't run that.

When I now run it, it still fails.

Am I supposed to run it with `localicious render ./copy.yaml` or `localicious render ./LocaliciousConfig.yaml`? Both result in different errors. I don't have a file named copy.yaml but the docs mention this so I'm not sure if it's supposed to be the output or input file.

When running `localicious render LocaliciousConfig.yaml . --platforms android --languages en` I get the following:
```
let result = Object.keys(data).map(key => {
                      ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at aggregate (/Users/lwesterhoff/Developer/forks/localicious/src/actions/normalize.js:28:23)
    at /Users/lwesterhoff/Developer/forks/localicious/src/actions/normalize.js:17:24
    at Array.map (<anonymous>)
    at normalizeYaml (/Users/lwesterhoff/Developer/forks/localicious/src/actions/normalize.js:17:8)
    at render (/Users/lwesterhoff/Developer/forks/localicious/src/actions/render.js:10:24)
    at /Users/lwesterhoff/Developer/forks/localicious/src/actions/validateAndRender.js:14:22
    at Result.flatMap (/Users/lwesterhoff/Developer/forks/localicious/src/utils/result.js:42:17)
    at validateAndRender (/Users/lwesterhoff/Developer/forks/localicious/src/actions/validateAndRender.js:14:6)
    at Object.<anonymous> (/Users/lwesterhoff/Developer/forks/localicious/bin/localicious-render:44:1)
```

Contents of LocaliciousConfig.yaml:
```
shared:
  eneco:
    company:
      name:
        en: 'Test'
        nl: 'Test'
```

**Comment by larslockefeer** [comment]
I'll update the `Requirements and installation`, it is indeed still a placeholder.

As for your other question, we have two commands:

`localicious render <localicipe_path>`: Renders a Localicipe. A Localicipe is the YAML file that contains the copy. It should indeed look like what you posted above.

`localicious install <localicious_config_path>`: Pulls a Localicipe from the source configured in  the provided localicious config and renders it for the languages and platforms configured in the same file.

A LocaliciousConfig looks [like this](https://github.com/PicnicSupermarket/localicious/blob/master/tests/localicious_config.yaml).

The error you are running into looks like a bug. If you change your Localicipe to the following, it should work:

```
shared:
  eneco:
    company:
      name:
        en: 'Test'
        nl: 'Test'
ios: {}
android: {}
```

We'll fix this before we hit 1.0.

**Comment by lammertw** [comment]
I've changed the contents to exactly that and now I get this:
```
❌ Something went wrong rendering.
Something went wrong.
```

**Comment by larslockefeer** [comment]
Can you share the command that you used to run it?

**Comment by lammertw** [comment]
`node path_to_localicious/bin/localicious render LocaliciousConfig.yaml . --platforms android --languages en`

**Comment by larslockefeer** [comment]
Thanks, I see what the problem is, it is because you are running it from outside the repository directory. I'll fix that!

Can you confirm that it works if you run it from within the directory? So: `node bin/localicious render path/to/localicipe.yaml . --platforms android --languages en`?

**Comment by lammertw** [comment]
Yes, that does seem to work.
When I now set the output path to some other folder it seems to completely ignore that and just puts it in the `render` folder of the working directory.

**Comment by lammertw** [comment]
I also thought that it would generate code for iOS (the enum code for iOS presented last week at CocoaheadsNL) but I only see the .strings files.

**Comment by larslockefeer** [comment]
Yep, we still need to push that to this repo (we rewrote our internal implementation). It will be done before we hit 1.0.

**Comment by larslockefeer** [comment]
@lammertw The issues discussed above should be resolved now. We'll add code generation next week and push 1.0 to npm.
